nginx:
  service:
    # connect LoadBalancer directly to VMs' internal IP
    # You get this value with: $ hostname -I
    externalIPs: [10.164.0.3]
rasax:
    # initialUser is the user which is created upon the initial start of Rasa X
    initialUser:
        # password for the Rasa X user
        password: "rasa"
    # passwordSalt Rasa X uses to salt the user passwords
    passwordSalt: "DrI5pGqKWL"
    # token Rasa X accepts as authentication token from other Rasa services
    token: "0nyoeQnm9x"
    # jwtSecret which is used to sign the jwtTokens of the users
    jwtSecret: "TyLfB5BS52"
    # tag refers to the Rasa X image tag
    tag: 0.38.0
rasa:
    # token Rasa accepts as authentication token from other Rasa services
    token: "biibMXyc4K"
    # tag refers to the Rasa image tag
    name: johan1us/rasa-core
    tag: 1
    versions:
      rasaProduction:
        replicaCount: 1
      rasaWorker:
        replicaCount: 1
rabbitmq:
    # rabbitmq settings of the subchart
    rabbitmq:
        # password which is used for the authentication
        password: "nfSnwtEJnx"
global:
    # postgresql: global settings of the postgresql subchart
    postgresql:
        # postgresqlPassword is the password which is used when the postgresqlUsername equals "postgres"
        postgresqlPassword: "O4HtoUKSU6"
    # redis: global settings of the postgresql subchart
    redis:
        # password to use in case there no external secret was provided
        password: "5KJ5UDCZdH"
#ingress:
#  annotations:
#    ingress.annotations.certmanager.k8s.io/cluster-issuer: letsencrypt-prod
#    kubernetes.io/ingress.class: traefik
#  hosts:
#    - host: answers-ai-assistants.com
#      paths:
#      - /
#  tls:
#   - secretName: ssl-certificate-secrete-name
#     hosts:
#       - answers-ai-assistants.com